// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechTreeAPI.SqlServe.DataBase;

namespace TechTreeAPI.SqlServe.Migrations
{
    [DbContext(typeof(TechTreeDbContext))]
    [Migration("20230416082306_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TechTreeAPI.Model.Main.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BuildName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("MaxCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Builds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildName = "CommandCenter",
                            Cost = 1000,
                            MaxCount = 1
                        },
                        new
                        {
                            Id = 2,
                            BuildName = "Power",
                            Cost = 1200,
                            MaxCount = 2
                        },
                        new
                        {
                            Id = 3,
                            BuildName = "Barracks",
                            Cost = 1300,
                            MaxCount = 1
                        },
                        new
                        {
                            Id = 4,
                            BuildName = "Defences",
                            Cost = 1100,
                            MaxCount = 3
                        },
                        new
                        {
                            Id = 5,
                            BuildName = "Mine",
                            Cost = 1500,
                            MaxCount = 2
                        },
                        new
                        {
                            Id = 6,
                            BuildName = "Airport",
                            Cost = 2000,
                            MaxCount = 2
                        },
                        new
                        {
                            Id = 7,
                            BuildName = "WarFactory",
                            Cost = 1500,
                            MaxCount = 3
                        },
                        new
                        {
                            Id = 8,
                            BuildName = "StrategyCenter",
                            Cost = 1700,
                            MaxCount = 1
                        },
                        new
                        {
                            Id = 9,
                            BuildName = "Hospital",
                            Cost = 2500,
                            MaxCount = 1
                        },
                        new
                        {
                            Id = 10,
                            BuildName = "Radar",
                            Cost = 900,
                            MaxCount = 10
                        },
                        new
                        {
                            Id = 11,
                            BuildName = "NuclearPower",
                            Cost = 4000,
                            MaxCount = 1
                        },
                        new
                        {
                            Id = 12,
                            BuildName = "SuperWeapon",
                            Cost = 2500,
                            MaxCount = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
